# Dependencies
markdown:         redcarpet
highlighter:      pygments
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty # tells what your website links will look like. For example: /blog/:year/:month/:day/:title/
relative_permalinks: false

# Setup
title:            Soundarya Ramesh
#tagline:          'A Jekyll theme'
description:      'PhD student in Computer Science.'
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://soundaryaramesh.github.io 
baseurl:          / 

author:
  name:           'Soundarya Ramesh'
  #url:            https://twitter.com/mdo

paginate:         1
#paginate_path:    "/_posts/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/soundaryaramesh/
