# Dependencies
markdown:         kramdown
highlighter:      rogue
mathjax:          true
#plugins:          [jekyll-paginate]
plugins:
 - jekyll-paginate

# Permalinks
permalink:        pretty # tells what your website links will look like. For example: /blog/:year/:month/:day/:title/
relative_permalinks: false

# Setup
title:            Soundarya Ramesh
#tagline:          'A Jekyll theme'
description:      Ph.D Candidate, NUS
#description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              "https://soundaryaramesh.github.io/"
baseurl:          "" 

author:
  name:           'Soundarya Ramesh'
  #url:            https://twitter.com/mdo

gravatar_md5:    3b2825418e1aca9e4dae39ea61f62fc5


paginate:         1
paginate_path:    "/blogs/page:num/"
#paginate_path:    "/_posts/page:num/"


github:
  repo:           https://github.com/soundaryaramesh/
